/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertForm: typeof import('./src/components/AlertForm.vue')['default']
    DashboardForm: typeof import('./src/components/dashboard/DashboardForm.vue')['default']
    DashboardList: typeof import('./src/components/dashboard/DashboardList.vue')['default']
    FilterKeyValueEditor: typeof import('./src/components/dashboard/FilterKeyValueEditor.vue')['default']
    MetricChart: typeof import('./src/components/MetricChart.vue')['default']
    NotificationsDropdown: typeof import('./src/components/NotificationsDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLanguage: typeof import('./src/components/SelectLanguage.vue')['default']
    TaskAssignDialog: typeof import('./src/components/tasks/TaskAssignDialog.vue')['default']
    TaskListView: typeof import('./src/components/tasks/TaskListView.vue')['default']
    ToastsList: typeof import('./src/components/ToastsList.vue')['default']
  }
}
