/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertForm: typeof import('./src/components/AlertForm.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    DashboardForm: typeof import('./src/components/dashboard/DashboardForm.vue')['default']
    DashboardList: typeof import('./src/components/dashboard/DashboardList.vue')['default']
    FilterKeyValueEditor: typeof import('./src/components/dashboard/FilterKeyValueEditor.vue')['default']
    MetricChart: typeof import('./src/components/MetricChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
